[build]
  command = "lerna bootstrap --no-ci && cd packages/backend && npm run build && rm -rf ../frontend/node_modules && rm -rf node_modules && rm -rf ../../node_modules"
  functions = "packages/backend/dist"