[build]
  command = "npm i && lerna bootstrap --no-ci && cd packages/backend && tsc && rm -rf ../frontend/node_modules && rm -rf node_modules && rm -rf ../../node_modules"
  functions = "packages/backend/src"