swagger: '2.0'
info:
  title: API Documentation
  version: 1.0.0
paths:
  /api/users:
    get:
      responses: {}
      tags:
        - Users
      summary: Get all Users
  /:
    '':
      responses: {}
      tags:
        - Users
      summary: Get User by UUID
tags:
  - name: Users
    description: Users controller
