swagger: '2.0'
info:
  title: API Documentation
  version: 1.0.0
paths:
  /api/users:
    get:
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              type: object
              properties:
                uuid:
                  type: string
                firstName:
                  type: string
                lastName:
                  type: string
          examples:
            application/json:
              - uuid: 38115282-3d12-4d20-87d2-60c1611e699c
                firstName: Mike
                lastName: Gajda
      tags:
        - Users
      summary: Get all Users
  '/api/user/{uuid}':
    get:
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              uuid:
                type: string
              firstName:
                type: string
              lastName:
                type: string
          examples:
            application/json:
              uuid: 38115282-3d12-4d20-87d2-60c1611e699c
              firstName: Mike
              lastName: Gajda
      tags:
        - Users
      summary: Get User by UUID
      parameters:
        - type: string
          description: uuid of this user
          name: uuid
          in: path
          required: true
tags:
  - name: Users
    description: Users controller
